# This is a config file with more options than you would find in config.yml.
# For the most part, these options just allow you to specify things per entity.
# The options in the standard config.yml will still be used as a default when you have not specified something in here.

# Don't change this!
version: 2


# Be sure to remove any comment markers (the #'s) to activate an option!
# You can find a list of entity types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# Make sure to use all caps for the entity types. It is case sensitive.

# Should we stop mobs from targeting mobs of the following type that are frozen?
prevent-targeting-frozen:
#  VILLAGER: true
#  WANDERING_TRADER: true

# Should we stop mobs from being able to damage frozen mobs of the following type?
prevent-damaging-frozen:
#  VILLAGER: true
#  WANDERING_TRADER: true

# Should we stop players from being able to damage frozen mobs of the following type?
prevent-player-damaging-frozen:
#  WOLF: true
#  CAT: true


# Should we unfreeze mobs of the following type when they are interacted with?
unfreeze-on-interact:
#  HORSE: true
#  DONKEY: true
#  MULE: true
#  SKELETON_HORSE: true

# For mobs of the following type, below what TPS should we ignore the unfreeze-on-interact option and never unfreeze those that are interacted with?
# Set to 0 to disable this option.
unfreeze-on-interact-tps-threshold:
#  HORSE: 10.0
#  DONKEY: 10.0
#  MULE: 10.0

# Should we unfreeze mobs of the following types when they take damage?
unfreeze-on-damage:
#  ZOMBIE: true
#  SKELETON: true
#  CREEPER: true

# For mobs of the following type, below what TPS should we ignore the unfreeze-on-damage option and never unfreeze those that are damaged?
# Set to 0 to disable this option.
unfreeze-on-damage-tps-threshold:
#  ZOMBIE: 10.0
#  SKELETON: 10.0
#  CREEPER: 10.0

# Should mobs of the following type that are tamed never be frozen?
ignore-tamed:
#  HORSE: true
#  DONKEY: true
#  MULE: true
#  SKELETON_HORSE: true
#  WOLF: false
#  CAT: false

# For mobs of the following type, below what TPS should we ignore the ignore-tamed option and not ignore those that are tamed?
# Set to 0 to disable this option.
ignore-tamed-tps-threshold:
#  HORSE: 10.0
#  DONKEY: 10.0
#  MULE: 10.0
#  SKELETON_HORSE: 10.0
#  WOLF: 15.0
#  CAT: 15.0

# Should mobs of the following type that are named with a name tag never be frozen?
ignore-named:
#  WOLF: true
#  CAT: true

# For mobs of the following type, below what TPS should we ignore the ignore-named option and not ignore those that are named?
# Set to 0 to disable this option.
ignore-named-tps-threshold:
#  WOLF: 10.0
#  CAT: 10.0

# Should mobs of the following type that are leashed never be frozen?
ignore-leashed:
#  HORSE: true
#  DONKEY: true
#  MULE: true

# For mobs of the following type, below what TPS should we ignore the ignore-leashed option and not ignore those that are leashed?
# Set to 0 to disable this option.
ignore-leashed-tps-threshold:
#  COW: 10.0
#  PIG: 10.0
#  SHEEP: 10.0
#  CHICKEN: 10.0
#  HORSE: 5.0
#  DONKEY: 5.0
#  MULE: 5.0

# Should mobs of the following type that are in love mode (breeding mode) never be frozen?
ignore-love-mode:
#  CHICKEN: false
#  COW: false
#  PIG: false
#  HORSE: true

# For mobs of the following type, below what TPS should we ignore the ignore-love-mode option and not ignore those that are in love mode?
# Set to 0 to disable this option.
ignore-love-mode-tps-threshold:
#  COW: 10.0
#  PIG: 10.0
#  SHEEP: 10.0
#  CHICKEN: 10.0
#  HORSE: 5.0
#  DONKEY: 5.0
#  MULE: 5.0

# Should mobs of the following type not be frozen when they are within the specified distance of a player?
# Note that this is quite an expensive check. If you have a lot of players it may make the freezing operation last significantly longer.
# Set to 0 to disable this option.
ignore-player-proximity:
#  ZOMBIE: 5.0
#  SKELETON: 5.0
#  CREEPER: 5.0

# For mobs of the following type, below what TPS should we ignore the ignore-player-proximity distance and start freezing those mobs?
# Set to 0 to disable this option.
ignore-player-proximity-tps-threshold:
#  ZOMBIE: 10.0
#  SKELETON: 10.0
#  CREEPER: 10.0

# Should mobs of the following type that are younger than the given number of ticks not be frozen?
ignore-younger-than-ticks:
#  ZOMBIE: 600
#  SKELETON: 600
#  CREEPER: 600
#  SPIDER: 600

# For mobs of the following type, below what TPS should we ignore the option above and start freezing mobs with ages above the given number of ticks.
# Set to 0 to disable this option.
ignore-younger-than-ticks-tps-threshold:
#  ZOMBIE: 10.0
#  SKELETON: 10.0
#  CREEPER: 10.0
#  SPIDER: 10.0

# Should mobs of the following type that are targeting a player never be frozen?
ignore-target-player:
#  ZOMBIE: true
#  SKELETON: true
#  CREEPER: true
#  SPIDER: true
#  PIG: true
#  COW: true
#  CHICKEN: true

# For mobs of the following type, below what TPS should we ignore the option above and start freezing mobs that are targeting a player?
# Set to 0 to disable this option.
ignore-target-player-tps-threshold:
#  ZOMBIE: 10.0
#  SKELETON: 10.0
#  CREEPER: 10.0
#  SPIDER: 10.0
#  PIG: 15.0
#  COW: 15.0
#  CHICKEN: 15.0

# For mobs of the following type, below what TPS should we ignore the never-freeze list and start freezing those mobs?
# Set to 0 to disable this option.
never-freeze-tps-threshold:
#  VILLAGER: 10.0
#  WANDERING_TRADER: 10.0
#  PILLAGER: 10.0
#  VINDICATOR: 10.0
#  VEX: 10.0
#  WITCH: 10.0
#  RAVAGER: 10.0
#  ILLUSIONER: 10.0
#  EVOKER: 10.0