name: SAML
main: com.froobworld.saml.Saml
author: froobynooby
version: 1.3.4-dev1
api-version: 1.13
description: >
             Lightweight anti-mob lag plugin.
commands:
   saml:
    description: Base command for SAML.