name: SAML
main: com.froobworld.saml.Saml
author: froobynooby
version: 2.0.0
api-version: 1.13
description: >
             Plugin for reducing performance impact of mobs and farms.
commands:
   saml:
    description: Base command for SAML.
